name: auto docs build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build_docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Yarn Setup
      uses: DerYeger/yarn-setup-action@v1.0.1
      with:
        node-version: 18.x
        
    # install dependencies
    - name: install dependencies
      run: yarn install 
    
    # build
    - name: build
      run: yarn deploy
      
    # commit
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "docs: build"
